package com.example.ramanpreet_sehmbi

val majorListNames = arrayOf(
    "Architecture, General",
    "Asian Area Studies",
    "Agricultural Economics",
    "Art History, Criticism & Conservation",
    "Business Administration",
    "Communications",
    "Computing Science",
    "Child Care Services Management",
    "Design & Visual Communications",
    "Dance",
    "Dental Hygiene",
    "Education",
    "English/Language Arts",
    "Engineering",
    "Foreign Languages Education",
    "French Language & Literature",
    "Genetics",
    "Geological & Earth Sciences",
    "Horticulture Science",
    "History",
    "IATS",
    "International Relations",
    "Journalism, Broadcast",
    "Journalism, Print",
    "Kinesiology",
    "Literature",
    "Mathematics",
    "Neuroscience",
    "Optometry",
    "Physical Education",
    "Quality Control & Safety Technologies",
    "Respiratory Therapy",
    "Special Education",
    "Surgical Technology",
    "Therapy",
    "Transportation",
    "Urban Studies",
    "Urban Affairs",
    "Veterinary Medicine",
    "Wildlife & Wildlands Management",
    "Zoology",
)

val MONTHS_YEAR = arrayOf("Jan.", "Feb.", "Mar.", "Apr.", "May", "Jun.", "Jul.", "Aug.", "Sep.","Oct.","Nov.","Dec." )